{
 "title": "WSO2 Inbound Endpoint Metrics",
 "description": "This Dashboard provides an overview of Inbound Endpoints deployed in Enterprise Integrator Cluster.",
 "time": { "from": "2020-08-25T10:59:45.895Z", "to": "2020-08-25T11:14:45.895Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values(wso2_integration_service_up{service_type=\"inbound-endpoint\"}, service_name)"
   },
   {
    "name": "node",
    "label": "Node Name",
    "query": "label_values(wso2_integration_service_up{service_name=\"$service\"}, instance)"
   },
   { "name": "jaegerHost", "query": "${VAR_JAEGERHOST}" }
  ]
 },
 "panels": [
  { "title": "[[service]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(wso2_integration_service_up{service_name=\"[[service]]\"})"
    }
   ]
  },
  {
   "title": "All Request Count",
   "type": "stat",
   "description": "Displays all time request count served by this inbound endpoint. This will also include the error requests.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(wso2_integration_inbound_endpoint_request_count_total{service_name=\"[[service]]\"}[$__range])-min_over_time(wso2_integration_inbound_endpoint_request_count_total{service_name=\"[[service]]\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successful Request Count",
   "type": "stat",
   "description": "Displays approximate request count received by this inbound endpoint within the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(sum(max_over_time(wso2_integration_inbound_endpoint_request_count_total{service_name=\"[[service]]\"}[$__range])-min_over_time(wso2_integration_inbound_endpoint_request_count_total{service_name=\"[[service]]\"}[$__range])))-(sum(max_over_time(wso2_integration_inbound_endpoint_request_count_error_total{service_name=\"[[service]]\"}[$__range])-min_over_time(wso2_integration_inbound_endpoint_request_count_error_total{service_name=\"[[service]]\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "description": "Displays all time error count occurred within this inbound endpoint",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(wso2_integration_inbound_endpoint_request_count_error_total{service_name=\"[[service]]\"}[$__range])-min_over_time(wso2_integration_inbound_endpoint_request_count_error_total{service_name=\"[[service]]\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "stat",
   "description": "Displays percentage of error requests against total request count",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(wso2_integration_inbound_endpoint_request_count_error_total{service_name=\"[[service]]\"}[$__range])-min_over_time(wso2_integration_inbound_endpoint_request_count_error_total{service_name=\"[[service]]\"}[$__range]))/sum(max_over_time(wso2_integration_inbound_endpoint_request_count_total{service_name=\"[[service]]\"}[$__range])-min_over_time(wso2_integration_inbound_endpoint_request_count_total{service_name=\"[[service]]\"}[$__range]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Deployed Node Count",
   "type": "stat",
   "description": "Displays number of nodes this inbound endpoint is deployed.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(wso2_integration_service_up{service_name=\"[[service]]\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Displays the request rate for this inbound endpoint.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(wso2_integration_inbound_endpoint_request_count_total{service_name=\"[[service]]\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Displays error rate of this inbound endpoint.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(wso2_integration_inbound_endpoint_request_count_error_total{service_name=\"[[service]]\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "description": "Displays the response time of all requests served by this inbound endpoint in a heat map. Each tile will represent number of requests which fell in to the pre-defined time bucket during the bucket time span.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le)(increase(wso2_integration_inbound_endpoint_latency_seconds_bucket{service_name=\"[[service]]\", le=~\".+\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{service=\"{inboundendpoint:[[service]]}\"}"
    }
   ]
  }
 ]
}